site_name: Documentación Oficial
site_url: https://ymminnl.github.io/page-wiki/
# repo_url: https://github.com/ymminnl/page-wiki/
# edit_uri: edit/main/docs/

theme:
  name: material
  language: es
  icon:
    logo: material/book-open-page-variant
  favicon: assets/favicon.png
  
  palette:
    # Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    # Modo Oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Inicio: index.md
  - Manual Operativo:
    - Protocolo Helper: guias/helper.md
    - Protocolo Moderador: guias/moderador.md
    - Códigos de Sanción: guias/plantillas.md