site_name: Documentación Staff
site_url: https://ymminnl.github.io/page-wiki/

theme:
  name: material
  language: es
  icon:
    logo: material/book-open-page-variant
  favicon: assets/favicon.png
  
  # Tipografía estándar (Roboto) es la que mejor funciona en móviles
  font:
    text: Roboto
    code: Roboto Mono

  palette:
    # Modo Claro (Blue Grey profesional)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    # Modo Oscuro (Slate)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Inicio: index.md
  - Manuales:
    - Protocolo Helper: guias/helper.md
    - Protocolo Moderador: guias/moderador.md
  - Referencia:
    - Códigos de Sanción: guias/plantillas.md