site_name: Documentaci칩n Staff
site_url: https://ymminnl.github.io/page-wiki/

theme:
  name: material
  language: es
  icon:
    logo: material/book-open-page-variant
  favicon: assets/favicon.png
  
  font:
    text: Roboto
    code: Roboto Mono

  palette:
    # Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    # Modo Oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

# Plugins Activos
plugins:
  - search
  - git-revision-date-localized:
      type: timeago      # Muestra "Hace 2 horas", "Hace 5 minutos"
      locale: es         # En espa침ol
      fallback_to_build_date: true # Por si acaso no detecta git

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Inicio: index.md
  - Manuales:
    - Protocolo Helper: guias/helper.md
    - Protocolo Moderador: guias/moderador.md
  - Referencia:
    - C칩digos de Sanci칩n: guias/plantillas.md
