site_name: Documentación Oficial
site_url: https://ymminnl.github.io/page-wiki/

theme:
  name: material
  language: es
  # Logo e icono
  icon:
    logo: material/shield-account
  favicon: assets/favicon.png
  
  # Tipografía Moderna (Google Fonts)
  font:
    text: Inter
    code: JetBrains Mono

  palette:
    # Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    # Modo Oscuro (Slate es más elegante que el negro puro)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes # Permite que las secciones sean clicables
    - search.suggest
    - search.highlight
    - content.code.copy

# CSS Personalizado
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list # Necesario para clases CSS en markdown

nav:
  - Portal: index.md
  - Manuales:
    - Helper: guias/helper.md
    - Moderador: guias/moderador.md
  - Referencia:
    - Plantillas: guias/plantillas.md
